schemaName: wxy

dataSource:
 url: jdbc:mysql://49.232.142.65:3306/wxy?serverTimezone=UTC&useSSL=false
 username: wxy
 password: wxy
 connectionTimeoutMilliseconds: 30000
 idleTimeoutMilliseconds: 60000
 maxLifetimeMilliseconds: 1800000
 maxPoolSize: 50
 minPoolSize: 1

encryptRule:
 encryptors:
   aes_encryptor:
     type: AES #加解密器类型，可自定义或选择内置类型：MD5/AES
     props: #属性配置, 注意：使用AES加密器，需要配置AES加密器的KEY属性：aes.key.value
       aes.key.value: 123456abc
       query.with.cipher.column: false
 tables:
   db_proxy:
     columns:
       id:
         #plainColumn: user_plain        # 存储明文的字段,系统迁移前存在,以后不需要了
         cipherColumn: user_cipher      # 存储密文的字段
         #assistedQueryColumn: #辅助查询字段，针对ShardingQueryAssistedEncryptor类型的加解密器进行辅助查询
         encryptor: aes_encryptor #加密器名字


# schemaName: wxy

# dataSource:
#  url: jdbc:mysql://81.69.172.101:3306/wxy?serverTimezone=UTC&useSSL=false
#  username: wxy
#  password: wxy
#  connectionTimeoutMilliseconds: 30000
#  idleTimeoutMilliseconds: 60000
#  maxLifetimeMilliseconds: 1800000
#  maxPoolSize: 50

# encryptRule:
#  encryptors:
#    md5_ecryptor:
#      type: MD5
#  tables:
#    db_proxy:
#      columns:
#        id:
#          cipherColumn: user_plain # 存储密文的字段
#          encryptor: md5_ecryptor # 
